<hr/>
<h1><center>Data Collection && Wrangling - Phnom Penh</center></h1>
<hr/>

***

# Import Packages
***

In [1]:
# importing the required modules
import glob
# Import the neccessary modules for data manipulation and visual representation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as matplot
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

# Read the Data
***

In [2]:
# specifying the path to csv files
# change ur directory here based on pwd

path = "C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets"

# excel files in the path
file_list = glob.glob(path + "/raw_layer/kompong_cham" + "/*.xlsx")
file_list

['C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\APRIL-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\APRIL-2022.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\AUGUST-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\DECEMBER-2020.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\DECEMBER-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\FEBRUAEY-2022.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\FEBRUARY-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\JANUARY-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\JANUARY-2022.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\JULY-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\JUNE-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\MARCH-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\MARCH-2022.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\MAY-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\NOVEMBER-2020.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\NOVEMBER-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\OCTOBER-2020.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\OCTOBER-2021.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\SEPTEMBER-2020.xlsx',
 'C:/Users/osssa/Desktop/Projects II/Cambodia_Weather_Forcasting_Prediction_With_Time_Series/datasets/raw_layer/kompong_cham\\SEPTEMBER-2021.xlsx']

In [3]:
# list of excel files we want to merge.
# pd.read_excel(file_path) reads the excel
# data into pandas dataframe.
excl_list = []

for file in file_list:
    excl_list.append(pd.read_excel(file))

In [4]:
# create a new dataframe to store the
# merged excel file.

excl_merged = pd.DataFrame()

for excl_file in excl_list:
    # appends the data into the excl_merged
    # dataframe.
    excl_merged = excl_merged.append(excl_file, ignore_index=True)

# exports the dataframe into excel file with
# specified n
#excl_merged.to_excel('merge_files.xlsx', index=False)
excl_merged

,CE SAIN Weather Station KPC,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Export settings name: KPC Data
0,Export timeframe: Data from 01-04-2021 to 1-04...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Location: Kampong Cham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Line#,Date,Time,Water Content (m3/m3),Solar Radiation (W//m2),Rain (mm),RH (%),Wind Speed (m/s),Gust Speed (m/s),Wind Direction (Degree),Temperature (Celcius ),Dew Point (Celcius),NaN
4,1,21/04/01,00:00:00,0.7186,1,0,78.4,3,6,201,27.7,23.63,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56447,2877,21/07/30,23:00:00,-0.1169,1,0,95.9,0,0.7,111,24.63,23.96,NaN
56448,2878,21/07/30,23:15:00,-0.1528,1,0,95.8,0.3,1.3,122,24.87,24.19,NaN
56449,2879,21/07/30,23:30:00,-0.1179,1,0,95.8,0,1,128,24.85,24.16,NaN
56450,2880,21/07/30,23:45:00,-0.1778,1,0,95.5,0.3,1.3,128,24.94,24.21,NaN
56451,2881,21/07/31,00:00:00,-0.115,1,0,95.4,1,2,131,24.97,24.21,NaN

In [5]:
pd.set_option('display.max_columns', None)

data = excl_merged
data.head()

,CE SAIN Weather Station KPC,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Export settings name: KPC Data
0,Export timeframe: Data from 01-04-2021 to 1-04...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Location: Kampong Cham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Line#,Date,Time,Water Content (m3/m3),Solar Radiation (W//m2),Rain (mm),RH (%),Wind Speed (m/s),Gust Speed (m/s),Wind Direction (Degree),Temperature (Celcius ),Dew Point (Celcius),NaN
4,1,21/04/01,00:00:00,0.7186,1,0,78.4,3,6,201,27.7,23.63,NaN

In [6]:
#since there are some Unnecessary colums appear from merged sooo clean them out
columns = ['CE SAIN Weather Station', 'CE SAIN Weather Station RUA']
data.drop(columns, inplace=True, axis=1)
data.head()

KeyError: "['CE SAIN Weather Station' 'CE SAIN Weather Station RUA'] not found in axis"

In [7]:
# Rename Columns
# Renaming certain columns for better readability
data.rename(
    columns={'Unnamed: 1': 'date', 
                        'Unnamed: 2': 'time',
                        'Unnamed: 3': 'water_content',
                        'Unnamed: 4': 'solar_radiation',
                        'Unnamed: 5': 'rain',
                        'Unnamed: 6': 'temperature',
                        'Unnamed: 7': 'rh',
                        'Unnamed: 8' : 'wind_speed',
                        'Unnamed: 9' : 'gust_speed',
                        'Unnamed: 10' : 'wind_direction',
                        'Unnamed: 11' : 'dew_point',
}, inplace=True)

In [8]:
#moreover, I can see the number of rows which has the name of features 
data.drop(data[data.date == 'Date'].index, inplace=True)
data[data['date'] == 'date']

Empty DataFrame
Columns: [CE SAIN Weather Station KPC, date, time, water_content, solar_radiation, rain, temperature, rh, wind_speed, gust_speed, wind_direction, dew_point, Export settings name: KPC Data]
Index: []

In [9]:
#since there are some Unnecessary rows and null appear from merged sooo clean them out
data.dropna(subset=['date'], how='all', inplace=True)

In [10]:
#check the data is null or not
data.isnull().any()

CE SAIN Weather Station KPC        True
date                              False
time                              False
water_content                     False
solar_radiation                   False
rain                              False
temperature                       False
rh                                False
wind_speed                        False
gust_speed                        False
wind_direction                    False
dew_point                         False
Export settings name: KPC Data     True
dtype: bool

In [11]:
#check the data is null or not
data.isnull().sum()

CE SAIN Weather Station KPC       11332
date                                  0
time                                  0
water_content                         0
solar_radiation                       0
rain                                  0
temperature                           0
rh                                    0
wind_speed                            0
gust_speed                            0
wind_direction                        0
dew_point                             0
Export settings name: KPC Data    45040
dtype: int64

In [12]:
#save the dataset 
data.to_csv(path + "/intermediate_layer/kompong_cham/cleaned_dataset_kompong_cham.csv")